# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'TaskNumberTwo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings! 
  pod 'RealmSwift'

	target 'TaskNumberTwoTests' do
        inherit! :search_paths
        pod 'Nimble'
        pod 'Quick'
    end
  end

